# DO NOT EDIT DIRECTLY!
# This file was generated automatically by GenStackDefines.py
# on Thu, 06 Feb 2020 18:00:03
#

components = {
   0: "NULL",
   1: "OPENWSN",
   2: "IDMANAGER",
   3: "OPENQUEUE",
   4: "OPENSERIAL",
   5: "PACKETFUNCTIONS",
   6: "RANDOM",
   7: "RADIO",
   8: "IEEE802154",
   9: "IEEE802154E",
  10: "SIXTOP_TO_IEEE802154E",
  11: "IEEE802154E_TO_SIXTOP",
  12: "SIXTOP",
  13: "NEIGHBORS",
  14: "SCHEDULE",
  15: "SIXTOP_RES",
  16: "OPENBRIDGE",
  17: "IPHC",
  18: "FRAG",
  19: "FORWARDING",
  20: "ICMPv6",
  21: "ICMPv6ECHO",
  22: "ICMPv6ROUTER",
  23: "ICMPv6RPL",
  24: "OPENUDP",
  25: "OPENTCP",
  26: "OPENCOAP",
  27: "CJOIN",
  28: "OPENOSCOAP",
  29: "C6T",
  30: "CEXAMPLE",
  31: "CINFO",
  32: "CLEDS",
  33: "CSENSORS",
  34: "CSTORM",
  35: "CWELLKNOWN",
  36: "UECHO",
  37: "UINJECT",
  38: "RRT",
  39: "SECURITY",
  40: "USERIALBRIDGE",
  41: "UEXPIRATION",
  42: "UMONITOR",
  43: "CINFRARED",
  44: "TECHO",
}

errorDescriptions = {
   1: "node joined",
   2: "OSCOAP sequence number reached maximum value",
   3: "OSCOAP buffer overflow detected (code location {0})",
   4: "OSCOAP replay protection failed",
   5: "OSCOAP decryption and tag verification failed",
   6: "Aborted join process (code location {0})",
   7: "unknown transport protocol {0} (code location {1})",
   8: "unsupported port number {0} (code location {1})",
   9: "invalid checksum, expected 0x{:04x}, found 0x{:04x}",
  10: "wrong TCP state {0} (location {1})",
  11: "TCP connecting to port {0}",
  12: "TCP sending {0} bytes (in flight {1})",
  13: "TCP transmission buffer full, written {0}",
  14: "TCP connection established with port {0}",
  15: "invalid TCP header",
  16: "TCP state machine reset (in state {0}, location {1})",
  17: "TCP connection closed",
  18: "TCP failed to push to lower layer",
  19: "TCP retransmission (seqn: {0}, rto: {1})",
  20: "too many TCP options (option size: {0})",
  21: "receive buffer ran out of segments",
  22: "received an ack",
  23: "parsing sack block L-edge {0}, R-edge {1}",
  24: "received an echo request",
  25: "received an echo reply",
  26: "the received packet has expired",
  27: "packet expiry time reached, dropped",
  28: "unexpected DAO (code location {0}). A change maybe happened on dagroot node.",
  29: "unsupported ICMPv6 type {0} (code location {1})",
  30: "unsupported 6LoWPAN parameter {1} at location {0}",
  31: "no next hop for layer 3 destination {0:x}{1:x}",
  32: "invalid parameter",
  33: "invalid forward mode",
  34: "large DAGrank {0}, set to {1}",
  35: "packet discarded hop limit reached",
  36: "loop detected due to previous rank {0} lower than current node rank {1}",
  37: "upstream packet set to be downstream, possible loop.",
  38: "packet to forward is dropped (code location {0})",
  39: "fragmentation buffer overflowed ({0} fragments queued)",
  40: "invalid original packet size ({0} > {1})",
  41: "reassembled fragments into big packet (size: {0}, tag: {1})",
  42: "fast-forwarded all fragments with tag {0} (total size: {1})",
  43: "stored a fragment with offset {0} (currently in buffer: {1})",
  44: "failed to send fragment with tag {0} (offset: {1})",
  45: "reassembly or vrb timer expired for fragments with tag {0}",
  46: "fragmenting a big packet, original size {0}, number of fragments {1}",
  47: "neighbors table is full (max number of neighbor is {0})",
  48: "there is no sent packet in queue",
  49: "there is no received packet in queue",
  50: "schedule overflown",
  51: "sixtop return code {0} at sixtop state {1}",
  52: "there are {0} cells to request mote",
  53: "the cells reserved to request mote contains slot {0} and slot {1}",
  54: "wrong celltype {0} at slotOffset {1}",
  55: "unsupported IEEE802.15.4 parameter {1} at location {0}",
  56: "got desynchronized at slotOffset {0}",
  57: "synchronized at slotOffset {0}",
  58: "large timeCorr.: {0} ticks (code loc. {1})",
  59: "wrong state {0} in end of frame+sync",
  60: "wrong state {0} in startSlot, at slotOffset {1}",
  61: "wrong state {0} in timer fires, at slotOffset {1}",
  62: "wrong state {0} in start of frame, at slotOffset {1}",
  63: "wrong state {0} in end of frame, at slotOffset {1}",
  64: "maxTxDataPrepare overflows while at state {0} in slotOffset {1}",
  65: "maxRxAckPrepapare overflows while at state {0} in slotOffset {1}",
  66: "maxRxDataPrepapre overflows while at state {0} in slotOffset {1}",
  67: "maxTxAckPrepapre overflows while at state {0} in slotOffset {1}",
  68: "wdDataDuration overflows while at state {0} in slotOffset {1}",
  69: "wdRadio overflows while at state {0} in slotOffset {1}",
  70: "wdRadioTx overflows while at state {0} in slotOffset {1}",
  71: "wdAckDuration overflows while at state {0} in slotOffset {1}",
  72: "security error on frameType {0}, code location {1}",
  73: "getData asks for too few bytes, maxNumBytes={0}, fill level={1}",
  74: "the input buffer has overflown",
  75: "busy sending",
  76: "sendDone for packet I didn't send",
  77: "no free packet buffer (code location {0})",
  78: "no free timer or queue entry (code location {0})",
  79: "freeing unused memory",
  80: "freeing memory unsupported memory",
  81: "unsupported command {0}",
  82: "unknown message type {0}",
  83: "wrong address type {0} (code location {1})",
  84: "bridge mismatch (code location {0})",
  85: "header too long, length {1} (code location {0})",
  86: "input length problem, length={0}",
  87: "booted",
  88: "invalid serial frame",
  89: "invalid packet from radio, length {1} (code location {0})",
  90: "busy receiving when stop of serial activity, buffer input length {1} (code location {0})",
  91: "wrong CRC in input Buffer",
  92: "synchronized when received a packet",
  93: "the slot {0} to be added is already in schedule",
  94: "the received packet format is not supported (code location {0})",
  95: "the metadata type is not suppored",
  96: "maxretries reached (counter: {0})",
  97: "empty queue or trying to remove unknown timer id (code location {0})",
}

sixtop_returncode = {
   0: "RC_SUCCESS",
   1: "RC_EOL",
   2: "RC_ERROR",
   3: "RC_RESET",
   4: "RC_VER_ERR",
   5: "RC_SFID_ERR",
   6: "RC_SEQNUM_ERR",
   7: "RC_CELLLIST_ERR",
   8: "RC_BUSY",
   9: "RC_LOCKED",
}

sixtop_statemachine = {
   0: "IDLE",
   1: "WAIT_ADDREQUEST_SENDDONE",
   2: "WAIT_DELETEREQUEST_SENDDONE",
   3: "WAIT_RELOCATEREQUEST_SENDDONE",
   4: "WAIT_COUNTREQUEST_SENDDONE",
   5: "WAIT_LISTREQUEST_SENDDONE",
   6: "WAIT_CLEARREQUEST_SENDDONE",
   7: "WAIT_ADDRESPONSE",
   8: "WAIT_DELETERESPONSE",
   9: "WAIT_RELOCATERESPONSE",
  10: "WAIT_COUNTRESPONSE",
  11: "WAIT_LISTRESPONSE",
  12: "WAIT_CLEARRESPONSE",
}
